# -*- coding: utf-8 -*-
"""
/***************************************************************************
 JoinTable
                                 A QGIS plugin
 Perform joins between spatial and non spatial tables
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-09
        copyright            : (C) 2019 by Francisco Camello N
        email                : franciscocamellon@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load JoinTable class from file JoinTable.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .join_tables import JoinTable
    return JoinTable(iface)
